name: davidanaya.io
title: davidanaya.io
description: Tech Lead at Telefonica Alpha

baseurl: ""
paginate_path: "page/page:num/"
permalink: none

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

# navigation:
#   - title: Home
#     url: /index.html
#   - title: About
#     url: /about

social:
  github: davidanaya
  twitter: danaya77

google_analytics: ""
